_target_: src.models.cgan_module.CondParticleGANModule
noise_dim: 128
num_particle_ids: 322
num_output_hadrons: 2
num_particle_kinematics: 2

optimizer_generator:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00001
  betas: [0.5, 0.999]
  weight_decay: 0.0

optimizer_discriminator:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00005
  betas: [0.5, 0.999]
  weight_decay: 0.0

scheduler_generator:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

scheduler_discriminator:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

generator:
  _target_: src.models.components.mlp.MyMLPMoudle
  input_dim: 136
  hidden_dims: [256, 256]
  output_dim: 646
  layer_norm: true
  dropout: 0.0


discriminator:
  _target_: src.models.components.mlp.MyMLPMoudle
  input_dim: 656
  hidden_dims: [128, 128]
  output_dim: 1
  layer_norm: true
  dropout: 0.0
