_target_: src.models.cgan.cond_event_gan.CondEventGANModule
noise_dim: 128
cond_info_dim: 4
num_particle_ids: 322
num_output_particles: 2
num_particle_kinematics: 2

optimizer_generator:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00001

optimizer_discriminator:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

generator:
  _target_: src.models.components.mlp.MLPModule
  # _target_: src.models.components.mlp_res.ResMLPModule
  input_dim: ${sum:${model.noise_dim},${model.cond_info_dim}} 
  hidden_dims: ${gen_list:256,2}
  output_dim: ${model.num_particle_kinematics}
  layer_norm: true
  dropout: 0.0

discriminator:
  _target_: src.models.components.deep_set.DeepSetModule
  input_dim: ${sum:${model.cond_info_dim},${model.num_particle_kinematics}}
  encoder_dims:  ${gen_list:128,2}
  decoder_dims: ${gen_list:128,2}
  output_dim: 1
  last_activation:
    _target_: torch.nn.Sigmoid

criterion:
  _target_: torch.nn.BCELoss

comparison_fn: null
  # _target_: src.metrics.compare_fn.CompareParticles
  # xlabels: ["phi", "eta"]
  # num_kinematics: ${model.num_particle_kinematics}
  # num_particles: ${model.num_output_particles}
  # num_particle_ids: ${model.num_particle_ids}
  # outdir: ${paths.output_dir}/images


