_target_: src.datamodules.gan_datamodule.ParticleGANDataModule
batch_size: 128
num_workers: 4
pin_memory: False
core_dataset:
  _target_: src.datamodules.components.herwig.Herwig
  data_dir: "${oc.env:HerwigData}/herwig"
  train_val_test_split: [5000, 100, 100]
