_target_: src.datamodules.herwig_datamodule.HerwigAllHadronsDataModule
data_dir: ${paths.data_dir}/herwig
batch_size: 128
train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 0
pin_memory: False